// react-apps/host-fe/src/components/app/App.jsx
import React, { lazy, Suspense } from 'react';

import ErrorBoundary from '../errorBoundary/ErrorBoundary';
import Search from 'remote/Search';
import Users from '../user/users/Users';

// const Search = lazy(() => import('./remote/Search'));

import { useLogic } from './hooks/useLogic';

import logo from '../../logo.svg';

const App = () => {
  const { filterUsers, handleOnSearch } = useLogic();

  console.log('<App />');

  return (
    <>
      <div className="header">
        <img src={logo} className="logo" alt="logo" />
        <div className="fake-header">{'{JSON} Placeholder'}</div>
      </div>
      <div className="app-container">
        <ErrorBoundary>
          <Search onSearch={handleOnSearch} />
        </ErrorBoundary>
        <Users users={filterUsers} />
      </div>
    </>
  );
}

export default App;

// solidjs-apps/remote-search/src/components/app/App.jsx
import { createSignal } from 'solid-js';

import Search from '../search/Search';

function App() {
  const [search, setSearch] = createSignal('');

  console.log('<App />');

  const handleOnSearch = search => setSearch(search);

  return (
    <div className="remote-container">
      <div>Remote Solid Search APP</div>
      <Search onSearch={handleOnSearch} />
      <div>{search}</div>
    </div>
  );
}

export default App;
